// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1AekuCEif5_jvcuJgvKPitL4rzcevfA8',
    appId: '1:1049103915491:web:5a8eaac35794d17170e8d6',
    messagingSenderId: '1049103915491',
    projectId: 'voyage-ddcee',
    authDomain: 'voyage-ddcee.firebaseapp.com',
    storageBucket: 'voyage-ddcee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3CRUCL8FtQuR9aGOgA_eaMU5qYo1ehqk',
    appId: '1:1049103915491:android:a5799010168c60f270e8d6',
    messagingSenderId: '1049103915491',
    projectId: 'voyage-ddcee',
    storageBucket: 'voyage-ddcee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN3orWFVxgnpoU8O2l-sJQ602j68pbGeM',
    appId: '1:1049103915491:ios:7729b310d147efdf70e8d6',
    messagingSenderId: '1049103915491',
    projectId: 'voyage-ddcee',
    storageBucket: 'voyage-ddcee.appspot.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN3orWFVxgnpoU8O2l-sJQ602j68pbGeM',
    appId: '1:1049103915491:ios:83136150e2cc808b70e8d6',
    messagingSenderId: '1049103915491',
    projectId: 'voyage-ddcee',
    storageBucket: 'voyage-ddcee.appspot.com',
    iosBundleId: 'com.example.voyage.RunnerTests',
  );
}
